clear all;
clc;
A=[0 1 0;0 0 1;-2 -5 -4];
B=[-7;19;-43];
C=[1 0 0];
D=0;
syms s t;
Gs=C*inv(s*eye(3)-A)*B+D;
eAt=ilaplace(inv(s*eye(3)-A));
minus_eAt=eAt*-1;
int_eAt=int(minus_eAt,t,0);
xt=int_eAt*B;
yt=C*xt;
AT=A';
CT=C';
sT = [0 0 1]*inv([CT, AT*CT, (AT^2)*CT]);
S=[sT;sT*AT;sT*AT*AT];
%L=acker(A',C',[-8;-8;-8]);
L=512*sT+192*sT*AT+24*sT*AT*AT+sT*AT*AT*AT;
L=L';
Aobs=[A-L*C];
Bobs=[B-L*D L];
Cobs=eye(3);
Dobs=zeros(3,2);